# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47f91af5f66247430e13072b7cdf57d6022013c74d39097988d93b35af40f206c0c35b414dd1a5e95d2ac4e63f208b6a8c70aa90c9b15606f5f21a886f450571

test:
  secret_key_base: a00beb6eb82d0266d8521a36431cac7f018a4b79acd8f25aafa6a32b923abf8d61c334734338ae637a8e92a11d1bc6e31faf03cb22878fc6bcb49e75fff7ad11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
